### ISSUE TITLE
Fitness Übungen und Workouts überarbeiten

### ISSUE THREAD

**Issue by Vadime** [Vadime/FitnessApp#35]
## Roadmap

- [x]  In WorkoutStatistik nicht Ids sondern richtige Kopien speichern vom Workout
- [x]  Beim Workout Design überlegen, wie man die (Reps, Sets, Weights bzw. Time) interaktiv ändert
- [x]  Das ganze richtig speichern im Backend und gucken ob alles immer noch funktioniert
- [x]  Beim Exercise Struktur anpassen um einen generellen Kalorienwert rein zu tun, der später mit deinen angaben zusammen gerechnet wird um den genauen Kalorienbedarf zu sehen
- [x]  In Workout, ausrechnen wie viele Kalorien es nimmt und es anzeigen (schon alles zusammengerechnet (alle Übungen zusammen mit eigener Health multipliziert))
- [x]  Als letztes im Health anzeigen wie viel man am Tag gegessen hat (bekommt man aus WorkoutStatistiks raus mit Filter by Day) 
- [x]  Feier dich junge, hast alles geschafft

**Comment by Vadime** [comment]
Die Kalorien von der Übung mit Health Einberechnung von persönlichen Faktoren (Größe, Alter und Sex) ist unklar. Deswegen machen wir das erstmal ohne, das heißt die Kalorien von den Übungen sind fest und für alle gleich.
